
package UI;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import logics.ImageLabel;


public class EncryptionFrame extends javax.swing.JFrame {

    int []pixels;
          int is;
    ArrayList al,zigzagal;
    int partitionsize=0;
    int _left=0;
            int partitions=0;
             String key="";
            int totalpartitions=0;
            String filename="";
            String bytestring="";
            StringBuilder partiondata;
    /** Creates new form EncryptionFrame */
    public EncryptionFrame() {
        al=new ArrayList();
        zigzagal=new ArrayList();
        initComponents();
  jPanel3.setVisible(false);
  for(int i=0;i<8;i++)
        bytestring+="0";
  
  partiondata=new StringBuilder();
      //  jPanel4.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(myproject.MyProjectApp.class).getContext().getResourceMap(EncryptionFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBounds(new java.awt.Rectangle(200, 100, 0, 0));
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setName("jTextField1"); // NOI18N

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.setName("jTextField2"); // NOI18N

        jButton8.setFont(resourceMap.getFont("jButton8.font")); // NOI18N
        jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(resourceMap.getFont("jButton9.font")); // NOI18N
        jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jPanel3.setBackground(resourceMap.getColor("jPanel3.background")); // NOI18N
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setName("jPanel3"); // NOI18N

        jButton2.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(resourceMap.getFont("jButton7.font")); // NOI18N
        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setName("jPanel4"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        MenuFrame mf=new MenuFrame();
        this.setVisible(false);
        mf.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //load an image here for processing
        JFileChooser jfc=new JFileChooser();
        FileNameExtensionFilter ext=new FileNameExtensionFilter("Image Files", "JPG");
        jfc.setFileFilter(ext);
        int rc=jfc.showOpenDialog(this);

        if(rc==JFileChooser.APPROVE_OPTION) 
        {
            filename=jfc.getSelectedFile().getAbsolutePath();
            jTextField1.setText(filename);
            ImageLabel imglbl=new ImageLabel(0,0,jPanel2.getBounds().height,jPanel2.getBounds().width,filename);
            jPanel2.removeAll();
        imglbl.revalidate();
        imglbl.repaint();
        jPanel2.add(imglbl); 
        jPanel2.revalidate();
        jPanel2.repaint();
        repaint();
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        //check the key in bits
        
        key=jTextField2.getText().trim();
        int length=key.length();
        if(length<8)
        {
            JOptionPane.showMessageDialog(this,"Invalid Key ReEnter");
            return;
        }
        if(length%4!=0)
        {
            JOptionPane.showMessageDialog(this,"Invalid Key Length");
            return;
        }
              
       String key=jTextField2.getText().trim();
       if(key.substring(0,4).equals("0000"))
       {
           JOptionPane.showMessageDialog(this,"Invalid Key No Partitions Can be Created ");
           return;
       }
        jPanel3.setVisible(true);
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private String convertToBits(int value)
    {
        String bitStream=bytestring;
        bitStream+=Integer.toBinaryString(value);
        bitStream=bitStream.substring(bitStream.length()-8,bitStream.length());  //return last 8 bits 
        return(bitStream);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            File f=new File(filename);
            BufferedImage buf=ImageIO.read(f);
            
            FileInputStream fis=new FileInputStream(f);
            
            pixels=new int[(int)f.length()];
            
            for(int i=0;i<pixels.length;i++)
                  pixels[i]=fis.read();
             JOptionPane.showMessageDialog(this,"Total Length "+pixels.length);
            //display all pixels onto the screen
           
      jTextArea1.setText("");
            String bits="";
            for(int i:pixels)
            {
                 bits=convertToBits(i);
                 jTextArea1.append(bits);
            }
            
            File fs=new File("C:\\_system");
            if(fs.exists()==false)
                fs.mkdir();
            
            FileOutputStream fos=new FileOutputStream("C:\\_system\\bin.txt");
            PrintWriter pw=new PrintWriter(fos);
            pw.println(jTextArea1.getText().trim());
            pw.close();
            fos.close();
            
            
            partiondata=new StringBuilder(jTextArea1.getText().trim());
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,"Invalid Operation" + ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    void CreatePartitions(int N)
    {
     
        //jTextArea1.setText("Creating Partitons Data For " + N + "  Partitions" );            
        double psize=Math.ceil((double)partiondata.length()/totalpartitions);
         partitionsize=(int)psize;
         JOptionPane.showMessageDialog(this,"Partitions " + totalpartitions+  " Size of each partition " + partitionsize);
         String data;
         
         int start;
        int bytepos=0;
         for(start=1;start<=N;start++)
         {
                data=partiondata.substring(((start-1)*partitionsize),(start*partitionsize));
                System.out.println("Partition " + start);
                al.add(data);
                bytepos+=partitionsize;
                if(bytepos+partitionsize>=partiondata.length())
                    break;
         }
         
         if(bytepos+partitionsize<partiondata.length())
         {
         while((bytepos+partitionsize)<partiondata.length())
         {
             data=partiondata.substring(bytepos,bytepos+partitionsize);
             al.add(data.trim());
             bytepos+=partitionsize;
         }
         data=partiondata.substring(bytepos);
  //       JOptionPane.showMessageDialog(this,"Last Partition size is " + data);
         al.add(data.trim());
         }
         else
         {
         data=partiondata.substring(bytepos);
         if(data.length()>0)
         {
  //       JOptionPane.showMessageDialog(this,"Last Partition size is " + data);
         al.add(data.trim());
         }
         }
         jTextArea1.setText("");
         //show partitions here
         for(int i=0;i<al.size();i++)
         {
           jTextArea1.append("\r\nPartition-" + (i+1)  +"\r\n");                 
           jTextArea1.append(al.get(i).toString().trim() + "\r\n");
           jTextArea1.append("<--------------->\r\n");
         }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //calculate partitions here so we can make partitions
        String key=jTextField2.getText();
        String leftfour=key.substring(0,4);
        partitions=Integer.valueOf(leftfour,2);
     //   JOptionPane.showMessageDialog(this,"Total Partitions "+ partitions);
        totalpartitions=(int)Math.pow(2, partitions);
        CreatePartitions(totalpartitions);
    }//GEN-LAST:event_jButton3ActionPerformed

    private StringBuilder makeZigZag(StringBuilder data)
    {
        //zigzag rule apply on the given data so it gets scrambled here
        String pdata=data.toString();
        String temp="";
        char []idata=pdata.toCharArray();
        String bitzigzag="";
        int lr=1;
        for(int i=0;i<idata.length;i++)
        {
                 if (lr == -1)
                {
                    temp = "";
                    for (int j = bitzigzag.length() - 1; j >= 0; j--)
                        temp += bitzigzag.toCharArray()[j];
                    bitzigzag = temp;
                    bitzigzag += idata[i];
                    temp = "";
                    for (int j = bitzigzag.length() - 1; j >= 0; j--)
                        temp += bitzigzag.toCharArray()[j];
                    bitzigzag = temp;
                    lr = 1;
                }
                else
                {
                    bitzigzag += idata[i];
                    lr = -1;
                }
        }
        return(new StringBuilder(bitzigzag));
    }
    
  
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //perform zigzag on each partition.
        
        
        StringBuilder sb;
        for(int i=0;i<al.size();i++)
        {
            sb=new StringBuilder(al.get(i).toString());
            zigzagal.add(makeZigZag(sb).toString());
        }
        jTextArea1.setText("\r\nZigZag Operations On Partions Done \r\n");
        for(int i=0;i<zigzagal.size();i++)
        {
                jTextArea1.append("\r\nParitition-" + (i+1) + "\r\n");
                jTextArea1.append(zigzagal.get(i).toString());
                jTextArea1.append("\r\n<-------->\r\n");
        }
       JOptionPane.showMessageDialog(this,"Zigzag Done On Paritions ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //perform swapping on the key after leaving four bits.
        
        String left=key.substring(4,key.length());
        String parkey="";
        int mypartition=0;
        int start=0;
        Object temp;
        for(int i=0;i<left.length();i+=4)
        {
            if(i==left.length()-4)
             parkey=left.substring(i);
            else
                parkey=left.substring(i,4);
             mypartition=Integer.parseInt(parkey,2);
             JOptionPane.showMessageDialog(this,"Exchange Partition " + start + " With " + mypartition);
             temp=zigzagal.get(start);
             zigzagal.set(start,zigzagal.get(mypartition));
             zigzagal.set(mypartition, temp);
             start++;
        }
        jTextArea1.setText("");
        for(int i=0;i<zigzagal.size();i++)
        {
             jTextArea1.append("Partitions After Swapping \r\n");
            jTextArea1.append("Parition - "+ (i+1) + "\r\n");
             jTextArea1.append(zigzagal.get(i).toString());
             jTextArea1.append("\r\n======\r\n");
        }
        JOptionPane.showMessageDialog(this,"Swapping Done on The Given Partitions ");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        //save encrypted image from last stage here
       StringBuilder sb=new StringBuilder();
        JOptionPane.showMessageDialog(this,"Total size is " + zigzagal.size());
        for(int i=0;i<zigzagal.size();i++)
            sb.append(zigzagal.get(i).toString().trim());
        
       JOptionPane.showMessageDialog(this,"Encrypted Data After All Operations ");
       jTextArea1.setText("");
       jTextArea1.setText(sb.toString());
       
       //save the content from the area into external image
       String bits="";
       int ascii=0;
       try
       {
       FileOutputStream fos=new FileOutputStream("C:\\Users\\ashnuman\\Desktop\\enc img\\newenc.jpg");
        for(is=0;is<sb.toString().trim().length();is+=8)
       {
            bits=sb.toString().substring(is,is+8);
            ascii=Integer.parseInt(bits,2);
            fos.write(ascii);
       }
       fos.close();
       //System.out.println("Value " + is);
    //   JOptionPane.showMessageDialog(this,"Byte pos " + is);
       JOptionPane.showMessageDialog(this,"Encrypted Image Created At C:\\Users\\ashnuman\\Desktop\\enc img\\newenc.jpg");
       
       fos=new FileOutputStream("C:\\Users\\ashnuman\\Desktop\\enc img\\keyinfo.txt");
       PrintWriter pw=new PrintWriter(fos);
       pw.println(jTextField2.getText());
       pw.close();
       fos.close();
       }
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this,"Error " + ex.getMessage() + "==>" + is);
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        MenuFrame mf=new MenuFrame();
        this.setVisible(false);
        mf.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void keyGenerate(int len)
    {
        Random r=new Random();
        String key="";
        for(int i=0;i<4;i++)
        {
            if(r.nextDouble()<0.3)
                key+="1";
            else
                key+="0";
        }
        
        for(int i=4;i<len;i++)
        {
          if(r.nextDouble()>0.5)
                key+="1";
            else
                key+="0";    
        }
        jTextField2.setText(key);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EncryptionFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
